{% set name = "graphene-tornado" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b00874814146f3802666e1bf4dd587a1098264888a89571408da19092930af81

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - pytest
  run:
    - python >=3.6
    - graphene >=2.1,<3
    - jinja2 >=2.10.1
    - six >=1.10.0
    - tornado >=5.1.0
    - werkzeug ==0.12.2

test:
  imports:
    - graphene_tornado

about:
  home: https://github.com/graphql-python/graphene-tornado
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A project for running Graphene on top of Tornado in Python 2 and 3.'

  description: |
    A project for running Graphene on top of Tornado in Python 2 and 3.
    The codebase is a port of graphene-django.
  doc_url: https://github.com/graphql-python/graphene-tornado
  dev_url: https://github.com/graphql-python/graphene-tornado

extra:
  recipe-maintainers:
    - kinow
